apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uzh1fax6b-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uzh1fax6b-python 
  name: uzh1fax6b-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uzh1fax6b-python 
